### ISSUE TITLE
Unable to use debug mode: AttributeError: 'Tracker' object has no attribute 'frame'

### ISSUE THREAD

**Issue by impana-c** [kocurvik/aicc#6]
Hello,
I get this error when I try change debug parameter from 0 to 1 in utils/tracker.py or when I try to set debug=1 inside run_single_video_serial.py:

Traceback (most recent call last):
  File "/home/cc/anaconda3/envs/aicc/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/cc/anaconda3/envs/aicc/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "run_single_video_threaded.py", line 88, in tracker_thread_fn
    tracker.step(dets)
  File "/data/cc/impana/aicc/utils/tracker.py", line 217, in step
    self.generate_entry(track)
  File "/data/cc/impana/aicc/utils/tracker.py", line 171, in generate_entry
    self.debug_track(positions[:, 0], positions[:, 1], corner_positiots_x, corner_positiots_y)
  File "/data/cc/impana/aicc/utils/tracker.py", line 97, in debug_track
    vis = np.copy(self.frame)
AttributeError: 'Tracker' object has no attribute 'frame'

**Comment by kocurvik** [comment]
This is probably a bug. You should try to use debug = 2 or some higher value. That should load the frame properly to display the debug outputs.

**Comment by impana-c** [comment]
Using a conda env with Python 3.7.
After setting debug=30, I get this error:

python run_single_video_serial.py /data/cc/impana/aic21/track1/Dataset_A/cam_1.mp4
Starting for video: /data/cc/impana/aic21/track1/Dataset_A/cam_1.mp4
QObject::moveToThread: Current thread (0x564a461e0920) is not the object's thread (0x564a4528a0b0).
Cannot move to target thread (0x564a461e0920)

qt.qpa.plugin: Could not load the Qt platform plugin "offscreen" in "/home/cc/anaconda3/envs/aicc/lib/python3.7/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, minimal, minimalegl, offscreen, vnc.

**Comment by impana-c** [comment]
Never mind, I have realized it is a problem with my ssh. Also, how can I train the network on my own in this project?

**Comment by kocurvik** [comment]
This project uses a network pretrained on MS COCO. No training scripts are available in this repository. If you want to train CenterTrack you can find training scripts in [the original CenterTrack repository](https://github.com/xingyizhou/CenterTrack).
